{"id":12803,"className":"java.beans.ExceptionListener","methodName":"exceptionThrown","signature":"\u003cjava.beans.ExceptionListener: void exceptionThrown(java.lang.Exception)\u003e","javadoc":"/** \n * This method is called when a recoverable exception has been caught.\n * @param e The exception that was caught.\n */\n","tf":{"freq":{"call":1,"thrown":1,"except":3,"method":1,"caught":2,"recover":1},"maxFreq":3,"totalTerms":9},"loc":0}