{"id":22291,"className":"org.apache.commons.math.MathRuntimeException","methodName":"MathRuntimeException","signature":"\u003corg.apache.commons.math.MathRuntimeException: void MathRuntimeException(java.lang.Throwable)\u003e","javadoc":"/** \n * Constructs a new \u003ccode\u003eMathRuntimeException\u003c/code\u003e with specified nested \u003ccode\u003eThrowable\u003c/code\u003e root cause.\n * @param rootCause  the exception or error that caused this exceptionto be thrown.\n */\n","tf":{"freq":{"exceptionto":1,"math":2,"thrown":1,"except":3,"caus":3,"error":1,"root":2,"nest":1,"runtim":2,"throwabl":1,"construct":1,"specifi":1},"maxFreq":3,"totalTerms":19},"loc":5}